name: Slaye
favicon: null
layout_spectrum: 0.33177
typography_spectrum: 0.71843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#161616'
    - '#5b5b5b'
    - '#888888'
    - '#d44d1d'
  brandStrength: 0.5
  lightness: 0.30755104520358145
  saturation: 0.625
  rhythmicContrast: 0.925449508940801
purpose: []
